version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    env_file:
      - web_variables.env
    command: python3 manage.py startapp pnb
    volumes:
      - .:/code
    ports:
      - "8000:80"
    depends_on:
      - db